python test.py \
    --lossfn BCE \
    --optimizer SGD \
    --max-epoch 20 \
    --batch-size 1\
    --lr 0.01\
    --feature-size 2048\
    --gt list/gt-ucf-R.npy\
    --datasetname UCF \
    --windowsize 0.15\
    --pseudofile Unsup_labels/pseudo_labels_swap_90.npy\
    --conall concat_UCF\