python mainv2.py \
    --datasetname UCF \
    --model_type all_cnn \
    --feature-size 2048 \
    --train-batch-size 32 \
    --window-size 500 \
    --stride 500 \
    --temporal_kernel 5 \
    --pseudofile Unsup_labels/UCF_pseudo_labels_ng.npy \
    --train-conall-path ../C2FPL/concat_UCF.npy \
    --train-nalist-path list/nalist_i3d.npy \
    --test-conall-path Concat_test_10.npy \
    --test-nalist-path list/nalist_test_i3d.npy \
    --confidence-path list/UCF_confidence_scores.npy \
    --gt list/gt-ucf-R.npy \
    --max-epoch 30 \
    --lr 0.001