python mainv2.py \
    --datasetname ShanghaiTech \
    --model_type all_cnn \
    --feature-size 2048 \
    --train-batch-size 8\
    --window-size 20 \
    --stride 20 \
    --temporal_kernel 5 \
    --pseudofile Unsup_labels/SHT_pseudo_labels_ng_2.npy \
    --train-conall-path SHT_concat_train.npy \
    --train-nalist-path list/SHT_nalist_train.npy \
    --test-conall-path SHT_concat_test.npy \
    --test-nalist-path list/SHT_nalist_test.npy \
    --gt list/gt-SHT-segment.npy\
    --confidence-path list/SHT_confidence_scores.npy\
    --max-epoch 40 \
    --lr 0.004