_wandb:
    value:
        cli_version: 0.23.0
        e:
            k1oj8jaur768ck1klds937fkyi4i7g0v:
                args:
                    - --use_variable_length
                    - --model_type
                    - all_cnn
                    - --batch_size_video
                    - "32"
                    - --temporal_kernel
                    - "5"
                    - --pseudofile
                    - Unsup_labels/pseudo_labels_swap_y.npy
                    - --max-epoch
                    - "30"
                codePath: mainv2.py
                codePathLocal: mainv2.py
                email: nayoung.kim.it@gmail.com
                executable: C:\Users\jplabuser\AppData\Local\Programs\Python\Python313\python.exe
                host: DESKTOP-56JKG4
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\jplabuser\코드 정리본\mainv2.py
                python: CPython 3.13.9
                root: C:\Users\jplabuser\코드 정리본
                startedAt: "2026-05-06T20:24:47.897961Z"
                writerId: k1oj8jaur768ck1klds937fkyi4i7g0v
        m: []
        python_version: 3.13.9
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 16
            "4": 3.13.9
            "5": 0.23.0
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
accumulation_steps:
    value: 1
batch_size:
    value: 128
batch_size_video:
    value: 32
conall:
    value: concat_UCF
datasetname:
    value: UCF
eps2:
    value: 0.4
feat_extractor:
    value: i3d
feature_size:
    value: 2048
gt:
    value: list/gt-ucf-RTFM.npy
lossfn:
    value: BCE
lr:
    value: 0.01
lstm_hidden:
    value: 64
max_epoch:
    value: 30
modality:
    value: RGB
model_name:
    value: C2FPL
model_type:
    value: all_cnn
modelversion:
    value: Model_V2
num_classes:
    value: 1
optimizer:
    value: SGD
outer_epochs:
    value: 1
pseudo:
    value: Unsup_labels/UCF_unsup_labels_original_V2.npy
pseudofile:
    value: Unsup_labels/pseudo_labels_swap_y.npy
rgb_list:
    value: ./list/ucf-c3d.list
stepsize:
    value: 5
temporal_kernel:
    value: 5
test_rgb_list:
    value: ./list/ucf-c3d-test.list
use_variable_length:
    value: true
windowsize:
    value: 0.09
workers:
    value: 0
